version: 2.1

orbs:
  win: circleci/windows@5.0.0
  macos: circleci/macos@2.5.2

jobs:
  windows_x86_64_compile:
    executor: win/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-{{ arch }}-{{ checksum "Cargo.toml" }}
            - cargo-{{ arch }}
      - run: choco install -y mingw nsis
      - run: curl.exe --output rustup-init.exe --url https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-gnu/rustup-init.exe
      - run: ./rustup-init.exe -vy
      - run: rustup toolchain install stable-x86_64-pc-windows-msvc
      - run: rustup default stable-x86_64-pc-windows-msvc
      # Install quality tools
      - run: |
          rustup component add clippy
          rustup component add rustfmt
          cargo install cargo-audit
      # Run checks
      - run: cargo clippy -- -D warnings
      - run: cargo fmt -- --check
      - run: cargo audit
      - run: cargo test --release --ignored
      - run: cargo build --release
      - save_cache:
          key: cargo-{{ arch }}-{{ checksum "Cargo.toml" }}
          paths:
            - ~/.cargo
  windows_x86_64_build:
    executor: win/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-{{ arch }}-{{ checksum "Cargo.toml" }}
            - cargo-{{ arch }}
      - run: choco install -y mingw nsis
      - run: curl.exe --output rustup-init.exe --url https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-gnu/rustup-init.exe
      - run: ./rustup-init.exe -vy
      - run: rustup toolchain install stable-x86_64-pc-windows-msvc
      - run: rustup default stable-x86_64-pc-windows-msvc
      - run: cargo build --release
      - run:
          name: push to jfrog
          command: | 
            $env:version = if ($env:CIRCLE_TAG) { $env:CIRCLE_TAG } else { if ($env:CIRCLE_BRANCH -eq "main") { "latest" } else { "prerelease" } }
            curl.exe -u samuel.hassine@filigran.io:$env:JFROG_TOKEN -T ./target/release/openbas-implant.exe "https://filigran.jfrog.io/artifactory/openbas-implant/windows/x86_64/openbas-implant-$env:version.exe"
      - save_cache:
          key: cargo-{{ arch }}-{{ checksum "Cargo.toml" }}
          paths:
            - ~/.cargo
  windows_arm_64_compile:
    machine: true
    resource_class: openbas-platform/openbas-agent-windows-64bits-arm
    shell: 'powershell.exe -ExecutionPolicy Bypass'
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-{{ arch }}-{{ checksum "Cargo.toml" }}
            - cargo-{{ arch }}
      - run: curl.exe -SL --output vs_buildtools.exe --url https://aka.ms/vs/17/release/vs_buildtools.exe
      - run: ./vs_buildtools.exe --add Microsoft.VisualStudio.Component.Clang --add Microsoft.VisualStudio.Component.VC.tools.arm64 --wait --includeRecommended --quiet --norestart
      - run: curl.exe --output rustup-init.exe --url https://static.rust-lang.org/rustup/dist/aarch64-pc-windows-msvc/rustup-init.exe
      - run: ./rustup-init.exe -vy
      - run: Invoke-Expression '& "$env:USERPROFILE\.cargo\bin\rustup" toolchain install stable-aarch64-pc-windows-msvc'
      - run: Invoke-Expression '& "$env:USERPROFILE\.cargo\bin\rustup" default stable-aarch64-pc-windows-msvc'
      # Install quality tools
      - run: |
          rustup component add clippy
          rustup component add rustfmt
          cargo install cargo-audit
      # Run checks
      - run: cargo clippy -- -D warnings
      - run: cargo fmt -- --check
      - run: cargo audit
      - run: cargo test --release --ignored
      - run: $env:PATH = "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\Llvm\ARM64\bin;" + $env:PATH; Invoke-Expression '& "$env:USERPROFILE\.cargo\bin\cargo" build --release'
      - save_cache:
          key: cargo-{{ arch }}-{{ checksum "Cargo.toml" }}
          paths:
            - ~/.cargo
  windows_arm_64_build:
    machine: true
    resource_class: openbas-platform/openbas-agent-windows-64bits-arm
    shell: 'powershell.exe -ExecutionPolicy Bypass'
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-{{ arch }}-{{ checksum "Cargo.toml" }}
            - cargo-{{ arch }}
      - run: curl.exe -SL --output vs_buildtools.exe --url https://aka.ms/vs/17/release/vs_buildtools.exe
      - run: ./vs_buildtools.exe --add Microsoft.VisualStudio.Component.Clang --add Microsoft.VisualStudio.Component.VC.tools.arm64 --wait --includeRecommended --quiet --norestart
      - run: curl.exe --output rustup-init.exe --url https://static.rust-lang.org/rustup/dist/aarch64-pc-windows-msvc/rustup-init.exe
      - run: ./rustup-init.exe -vy
      - run: Invoke-Expression '& "$env:USERPROFILE\.cargo\bin\rustup" toolchain install stable-aarch64-pc-windows-msvc'
      - run: Invoke-Expression '& "$env:USERPROFILE\.cargo\bin\rustup" default stable-aarch64-pc-windows-msvc'
      - run: $env:PATH = "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\Llvm\ARM64\bin;" + $env:PATH; Invoke-Expression '& "$env:USERPROFILE\.cargo\bin\cargo" build --release'
      - run:
          name: push to jfrog
          command: |
            $env:version = if ($env:CIRCLE_TAG) { $env:CIRCLE_TAG } else { if ($env:CIRCLE_BRANCH -eq "main") { "latest" } else { "prerelease" } }
            curl.exe -u samuel.hassine@filigran.io:$env:JFROG_TOKEN -T ./target/release/openbas-implant.exe "https://filigran.jfrog.io/artifactory/openbas-implant/windows/arm64/openbas-implant-$env:version.exe"
      - save_cache:
          key: cargo-{{ arch }}-{{ checksum "Cargo.toml" }}
          paths:
            - ~/.cargo
  linux_x86_64_compile:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-{{ arch }}-{{ checksum "Cargo.toml" }}
            - cargo-{{ arch }}
      - run: sudo apt-get update
      - run: sudo apt-get -y install curl musl-tools
      - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - run: . "$HOME/.cargo/env"; rustup target add x86_64-unknown-linux-musl
      # Install quality tools
      - run: |
          rustup component add clippy
          rustup component add rustfmt
          cargo install cargo-audit
      # Run checks
      - run: cargo clippy -- -D warnings
      - run: cargo fmt -- --check
      - run: cargo audit
      - run: cargo test --release --ignored
      - run: . "$HOME/.cargo/env"; cargo build --target=x86_64-unknown-linux-musl --release
      - run: strip ./target/x86_64-unknown-linux-musl/release/openbas-implant
      - save_cache:
          key: cargo-{{ arch }}-{{ checksum "Cargo.toml" }}
          paths:
            - ~/.cargo
  linux_x86_64_build:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-{{ arch }}-{{ checksum "Cargo.toml" }}
            - cargo-{{ arch }}
      - run: sudo apt-get update
      - run: sudo apt-get -y install curl musl-tools
      - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - run: . "$HOME/.cargo/env"; rustup target add x86_64-unknown-linux-musl
      - run: . "$HOME/.cargo/env"; cargo build --target=x86_64-unknown-linux-musl --release
      - run: strip ./target/x86_64-unknown-linux-musl/release/openbas-implant
      - run:
          name: push to jfrog
          command: | 
            export version=${CIRCLE_TAG:-$( [ "$CIRCLE_BRANCH" = "main" ] && echo "latest" || echo "prerelease" )}
            curl -usamuel.hassine@filigran.io:$JFROG_TOKEN -T ./target/x86_64-unknown-linux-musl/release/openbas-implant "https://filigran.jfrog.io/artifactory/openbas-implant/linux/x86_64/openbas-implant-$version"
      - save_cache:
          key: cargo-{{ arch }}-{{ checksum "Cargo.toml" }}
          paths:
            - ~/.cargo
  linux_arm_64_compile:
    machine:
      image: ubuntu-2204:current
    resource_class: arm.medium
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-{{ arch }}-{{ checksum "Cargo.toml" }}
            - cargo-{{ arch }}
      - run: sudo apt-get update
      - run: sudo apt-get -y install curl musl-tools
      - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - run: . "$HOME/.cargo/env"; rustup target add aarch64-unknown-linux-musl
      # Install quality tools
      - run: |
          rustup component add clippy
          rustup component add rustfmt
          cargo install cargo-audit
      # Run checks
      - run: cargo clippy -- -D warnings
      - run: cargo fmt -- --check
      - run: cargo audit
      - run: cargo test --release --ignored
      - run: . "$HOME/.cargo/env"; cargo build --target=aarch64-unknown-linux-musl --release
      - run: strip ./target/aarch64-unknown-linux-musl/release/openbas-implant
      - save_cache:
          key: cargo-{{ arch }}-{{ checksum "Cargo.toml" }}
          paths:
            - ~/.cargo
  linux_arm_64_build:
    machine:
      image: ubuntu-2204:current
    resource_class: arm.medium
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-{{ arch }}-{{ checksum "Cargo.toml" }}
            - cargo-{{ arch }}
      - run: sudo apt-get update
      - run: sudo apt-get -y install curl musl-tools
      - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - run: . "$HOME/.cargo/env"; rustup target add aarch64-unknown-linux-musl
      - run: . "$HOME/.cargo/env"; cargo build --target=aarch64-unknown-linux-musl --release
      - run: strip ./target/aarch64-unknown-linux-musl/release/openbas-implant
      - run:
          name: push to jfrog
          command: |
            export version=${CIRCLE_TAG:-$( [ "$CIRCLE_BRANCH" = "main" ] && echo "latest" || echo "prerelease" )}
            curl -usamuel.hassine@filigran.io:$JFROG_TOKEN -T ./target/aarch64-unknown-linux-musl/release/openbas-implant "https://filigran.jfrog.io/artifactory/openbas-implant/linux/arm64/openbas-implant-$version"
      - save_cache:
          key: cargo-{{ arch }}-{{ checksum "Cargo.toml" }}
          paths:
            - ~/.cargo
  macos_arm_64_compile:
    macos:
      xcode: 15.3.0
    resource_class: macos.m1.medium.gen1
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-{{ arch }}-{{ checksum "Cargo.toml" }}
            - cargo-{{ arch }}
      - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      # Install quality tools
      - run: |
          rustup component add clippy
          rustup component add rustfmt
          cargo install cargo-audit
      # Run checks
      - run: cargo clippy -- -D warnings
      - run: cargo fmt -- --check
      - run: cargo audit
      - run: cargo test --release --ignored
      - run: . "$HOME/.cargo/env"; cargo build --release
      - run: strip ./target/release/openbas-implant
      - save_cache:
          key: cargo-{{ arch }}-{{ checksum "Cargo.toml" }}
          paths:
            - ~/.cargo
  macos_arm_64_build:
    macos:
      xcode: 15.3.0
    resource_class: macos.m1.medium.gen1
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-{{ arch }}-{{ checksum "Cargo.toml" }}
            - cargo-{{ arch }}
      - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - run: . "$HOME/.cargo/env"; cargo build --release
      - run: strip ./target/release/openbas-implant
      - run:
          name: push to jfrog
          command: |
            export version=${CIRCLE_TAG:-$( [ "$CIRCLE_BRANCH" = "main" ] && echo "latest" || echo "prerelease" )}
            curl -usamuel.hassine@filigran.io:$JFROG_TOKEN -T ./target/release/openbas-implant "https://filigran.jfrog.io/artifactory/openbas-implant/macos/arm64/openbas-implant-$version"
      - save_cache:
          key: cargo-{{ arch }}-{{ checksum "Cargo.toml" }}
          paths:
            - ~/.cargo
  macos_x86_64_compile:
    machine: true
    resource_class: openbas-platform/openbas-agent-macos-64bits-x86
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-{{ arch }}-{{ checksum "Cargo.toml" }}
            - cargo-{{ arch }}
      - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      # Install quality tools
      - run: |
          rustup component add clippy
          rustup component add rustfmt
          cargo install cargo-audit
      # Run checks
      - run: cargo clippy -- -D warnings
      - run: cargo fmt -- --check
      - run: cargo audit
      - run: cargo test --release --ignored
      - run: . "$HOME/.cargo/env"; cargo build --release
      - run: strip ./target/release/openbas-implant
      - save_cache:
          key: cargo-{{ arch }}-{{ checksum "Cargo.toml" }}
          paths:
            - ~/.cargo
  macos_x86_64_build:
    machine: true
    resource_class: openbas-platform/openbas-agent-macos-64bits-x86
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-{{ arch }}-{{ checksum "Cargo.toml" }}
            - cargo-{{ arch }}
      - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - run: . "$HOME/.cargo/env"; cargo build --release
      - run: strip ./target/release/openbas-implant
      - run:
          name: push to jfrog
          command: |
            export version=${CIRCLE_TAG:-$( [ "$CIRCLE_BRANCH" = "main" ] && echo "latest" || echo "prerelease" )}
            curl -usamuel.hassine@filigran.io:$JFROG_TOKEN -T ./target/release/openbas-implant "https://filigran.jfrog.io/artifactory/openbas-implant/macos/x86_64/openbas-implant-$version"
      - save_cache:
          key: cargo-{{ arch }}-{{ checksum "Cargo.toml" }}
          paths:
            - ~/.cargo

workflows:
  openbas-implant:
    jobs:
      - windows_x86_64_compile:
          filters:
            tags:
              ignore: /.*/
            branches:
              ignore:
                - main
                - release/current
      - windows_x86_64_build:
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)+(\.[0-9]+)*/
            branches:
              only:
                - main
                - release/current
      - windows_arm_64_compile:
          filters:
            tags:
              ignore: /.*/
            branches:
              ignore:
                - main
                - release/current
      - windows_arm_64_build:
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)+(\.[0-9]+)*/
            branches:
              only:
                - main
                - release/current
      - linux_x86_64_compile:
          filters:
            tags:
              ignore: /.*/
            branches:
              ignore:
                - main
                - release/current
      - linux_x86_64_build:
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)+(\.[0-9]+)*/
            branches:
              only:
                - main
                - release/current
      - linux_arm_64_compile:
          filters:
            tags:
              ignore: /.*/
            branches:
              ignore:
                - main
                - release/current
      - linux_arm_64_build:
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)+(\.[0-9]+)*/
            branches:
              only:
                - main
                - release/current
      - macos_arm_64_compile:
          filters:
            tags:
              ignore: /.*/
            branches:
              ignore:
                - main
                - release/current
      - macos_arm_64_build:
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)+(\.[0-9]+)*/
            branches:
              only:
                - main
                - release/current
      - macos_x86_64_compile:
          filters:
            tags:
              ignore: /.*/
            branches:
              ignore:
                - main
                - release/current
      - macos_x86_64_build:
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)+(\.[0-9]+)*/
            branches:
              only:
                - main
                - release/current